# === MAIN CONFIG ==========================================
#   Self explanatory descriptions below.
# ==========================================================

# ==========================================================
#   This option will check for latest updates online.
#   It will not download anything, just notify you
#   if there is a new version of the plugin. If outdated,
#   the plugin will notify you every (update-interval)
#   seconds that is adjustible below.
# ==========================================================
update-checker: true
checker-interval: 600           # 600 seconds is 10 minutes.

# Options:
#      action or actionbar
#      boss or bossbar (Requires)
display: action

# ==========================================================
#   This option will send data such as player count and
#   java version to mcstats.org. Compassance uses
#   MetricsLite which will only send basic information.
#   You can check out what it collects at:
#      http://mcstats.org/plugin/Compassance
# ==========================================================
metrics: true

# ==========================================================
#   If this is enabled, all themes will not require
#   permission, but you can set certain themes to require
#   them by adding the 'permission' node in the 'meta'
#   section.
# ==========================================================
use-permissions: true

# ==========================================================
#   If this is enabled, players can enable tracking.
# ==========================================================
use-tracking: true

# ==========================================================
#   This feature enables you to (MAYBE) get some features
#   that I have left over or haven't fully implemented
#   yet. I won't even tell you what I added to the bleeding
#   edge option until I finally finish developing it.
# ==========================================================
bleeding-edge: false