# === PLAYER CONFIG ========================================
#   Here you will find all the player data text read
#   by the plugin. I do not recomend editing this while
#   the plugin is still running, as reloading will instantly
#   overwrite your changes with the server changes.
# ==========================================================

players:
  default:
    settings:
      selectedTheme: default
      enableCompass: true
      enableCursor: true
      alwaysOn: true
      tracking: false