name: ${project.artifactId}
author: Hexragon

website: ${project.url}

description: >
  Compassance is bold and original. Discover something you never thought that you wanted,
  a dynamic compass on your action bar. With amazing coding, simple GUI, self-theming
  capabilities, configurations, tracking and more; Compassance is a simple plugin
  that personalizes the Minecraft experience. Basically a cooler action bar.

softdepend: [PlaceholderAPI, BossBarAPI]
main: com.hexragon.compassance.Main
version: ${project.version}

commands:
  compass:
    description: Open up the compass settings menu.
    usage: /<command>
    aliases: [comp, compassance, cmps]
  test:
    description: hi
    usage: /<command>
  compass-admin:
      description: Open up the compass settings menu.
      usage: /<command>
      aliases: [comp-a, compassance-a, cmps-a, compass-a]
