name: Compassance
author: Hexragon
softdepend: [PlaceholderAPI]
main: com.hexragon.compassance.Compassance
version: 1.4-SNAPSHOT

description: A cooler action bar.

commands:
  compass:
    description: Open up the compass setting menu.
    usage: /<command>
  test:
    description: hi
    usage: /<command>
  tcomp:
      description: hi
      usage: /<command>
  test2:
    usage: /<command>