name: ${project.artifactId}
author: Hexragon

website: ${project.url}

description: >
  Compassance is bold and original. Discover something you never thought that you wanted,
  a dynamic compass on your action bar. With amazing coding, simple GUI, self-theming
  capabilities, configurations, tracking and more; Compassance is a simple plugin
  that personalizes the Minecraft experience. Basically a cooler action bar.

softdepend: [PlaceholderAPI]
main: com.hexragon.compassance.Main
version: ${project.version}

commands:
  compass:
    description: Open up the compass settings menu.
    usage: /<command>
    aliases: [comp, compassance, cmps]
  compass-admin:
      description: Open up the compass settings menu.
      usage: /<command>
      aliases: [comp-a, compassance-a, cmps-a, compass-a]

permissions:
  compassance.*:
    description: Gives access to all Compassance features.
    children:
      compassance.command: true
      compassance.admincommand: true
      compassance.theme.*: true
  compassance.command:
    description: Gives access to user compass command.
    default: true
  compassance.admincommand:
    description: Gives access to admin compass command.
    default: op
  compassance.theme.*:
    description: Give access to all themes.
    default: op