name: Compassance
author: hexSquared
main: com.hexsquared.compassance.Compassance
version: B0.1

description: A cooler compass.

commands:
  compass:
    description: Open up the compass setting menu.
    usage: /<command>
  test:
    description: hi
    usage: /<command>
  tcomp:
      description: hi
      usage: /<command>
  test2:
    usage: /<command>