# === THEMES CONFIG ========================================
#   Here you will find all the themes registered by the
#   plugin. Be careful to follow the default format and
#   read the theming guide or the plugin will start
#   spewing out nasty errors.
# ==========================================================

# ===== NOTE ===============================================
#   You should not mess with the version node, it is a way
#   for the plugin to detect if the templates do not match
#   a possible new version or updates. Back up this file
#   and download a new one if the plugin mentions any
#   errors regarding 'theme config outdated'.
# ==========================================================
version: 1.0

# === THEMING GUIDE ========================================
#
# ====== Main Pattern Map
#   This will dictate what characters will go where, what
#   sub patterns will go where, etc. It is highly recomended
#   that you follow the 'default' template provided, so that
#   data can be accurate and the plugin won't start throwing
#   all kinds of errors.
#
# ====== <?> - Direct Patterns
#   These keys will immediately point the generator towards
#   the 'patterns/direct-pattern' section and look for the
#   corresponding character to replace in the main map.
#   The generator will process them first.
#
# ====== <s/?> - Sub Patterns
#   These keys will point to the 'sub-pattern' section and
#   replace them in the main pattern map. During generation
#   of the compass string, the plugin will look for the
#   corresponding character and process them before the
#   post-process comes in.
#
# ====== Post Processing
#   <str> represents the generated string, post process will
#   not affect the direction of the compass at all, rather
#   only add on gimmicks such as brackets or the cursor
#   function, which is exclusive to post processing.
#
#   Separate keys by using ';'.
#
# ===== References
#   This is a work in progress. These values are generated
#   dynamically and it is not recomended that you name a
#   key after them.
#
#     <str>     Preprocessed string.
#
# ==========================================================
themes:
  default:
    meta:
      name: "&lMidnight"
      desc: "&7The default theme.%nl%&7The moon fills you with determination."
    data:
      main-pattern-map: "<S>;<s/sep>;<W>;<s/sep>;<N>;<s/sep>;<E>;<s/sep>"
      function:
        cursor: "&f[;<str>;&f]"
        target: "&9\u2588"
      direct:
        <S>: "&f&l&n S "
        <W>: "&f&l&n W "
        <N>: "&f&l&n N "
        <E>: "&f&l&n E "
      sub-pattern:
        <s/sep>:
          pattern-map: "<1>;<2>;<3>;<3>;<4>;<4>;<4>;<4>;<4>;<4>;<3>;<3>;<2>;<1>"
          <1>: "&0\u2588"
          <2>: "&0\u2593"
          <3>: "&0\u2592"
          <4>: "&0\u2591"
    final:
      pattern-map: "<<>;<str>;<>>"
      <<>: "&f&l["
      <>>: "&f&l]"
  midnight-light:
    meta:
      name: "&lMidnight Light"
      desc: "&7Light the night."
    data:
      main-pattern-map: "<S>;<s/sep>;<W>;<s/sep>;<N>;<s/sep>;<E>;<s/sep>"
      function:
        cursor: "&f[;<str>;&f]"
        target: "&9\u2588"
      direct:
        <S>: "&f&l&n S "
        <W>: "&f&l&n W "
        <N>: "&f&l&n N "
        <E>: "&f&l&n E "
      sub-pattern:
        <s/sep>:
          pattern-map: "<1>;<2>;<3>;<3>;<4>;<4>;<4>;<4>;<4>;<4>;<3>;<3>;<2>;<1>"
          <1>: "&8\u2588"
          <2>: "&8\u2593"
          <3>: "&8\u2592"
          <4>: "&8\u2591"
    final:
      pattern-map: "<<>;<str>;<>>"
      <<>: "&f&l["
      <>>: "&f&l]"
  midnight-mini:
    meta:
      name: "&lMidnight Mini"
      desc: "&7Baby moon-moon."
    data:
      main-pattern-map: "<S>;<s/sep>;<W>;<s/sep>;<N>;<s/sep>;<E>;<s/sep>"
      function:
        cursor: "&f[;<str>;&f]"
        target: "&9\u2588"
      direct:
        <S>: "&f&l&n S "
        <W>: "&f&l&n W "
        <N>: "&f&l&n N "
        <E>: "&f&l&n E "
      sub-pattern:
        <s/sep>:
          pattern-map: "<1>;<2>;<3>;<4>;<3>;<2>;<1>"
          <1>: "&0\u2588"
          <2>: "&0\u2593"
          <3>: "&0\u2592"
          <4>: "&0\u2591"
    final:
      pattern-map: "<<>;<str>;<>>"
      <<>: "&f&l["
      <>>: "&f&l]"
  midnight-color:
    meta:
      name: "&lRespendent"
      desc: "&7What does it mean!?"
    data:
      main-pattern-map: "<S>;<s/sep>;<W>;<s/sep>;<N>;<s/sep>;<E>;<s/sep>"
      function:
        cursor: "&f[;<str>;&f]"
        target: "&f&l\u2588"
      direct:
        <S>: "&f&l&n S "
        <W>: "&f&l&n W "
        <N>: "&f&l&n N "
        <E>: "&f&l&n E "
      sub-pattern:
        <s/sep>:
          pattern-map: "<1>;<2>;<3>;<4>;<5>;<6>;<7>;<8>;<9>;<a>;<b>;<c>"
          <1>: "&4\u2588"
          <2>: "&c\u2593"
          <3>: "&e\u2593"
          <4>: "&6\u2592"
          <5>: "&2\u2592"
          <6>: "&a\u2591"
          <7>: "&b\u2591"
          <8>: "&3\u2592"
          <9>: "&9\u2592"
          <a>: "&1\u2593"
          <b>: "&5\u2593"
          <c>: "&d\u2588"
    final:
      pattern-map: "<<>;<str>;<>>"
      <<>: "&f&l["
      <>>: "&f&l]"
