# === THEMES CONFIG ========================================
#   Here you will find all the themes registered by the
#   plugin. Be careful to follow the default format and
#   read the theming guide or the plugin will start
#   spewing out nasty errors.
# ==========================================================

# ===== NOTE ===============================================
#   You should not mess with the version node, it is a way
#   for the plugin to detect if the templates do not match
#   a possible new version or updates. Back up this file
#   and download a new one if the plugin mentions any
#   errors regarding 'theme configs outdated'.
# ==========================================================
version: 1.1

# === ENABLED THEMES =======================================
#   Themes from here will be registered upon loading.
#   'default' is always registered.
# ==========================================================
enabled-themes:
  - midnight-light
  - midnight-mini
  - midnight-color
  - minimal-normal
  - minimal-staff
  - locational-red
  - locational-blue
  - time-compass

# === THEMING GUIDE ========================================
#
# ====== Main Pattern Map
#   This will dictate what characters will go where, what
#   sub patterns will go where, etc. It is highly recomended
#   that you follow the 'default' template provided, so that
#   data can be accurate and the plugin won't start throwing
#   all kinds of errors.
#
# ====== <?> - Direct Patterns
#   These keys will immediately point the generator towards
#   the 'patterns/direct-pattern' section and look for the
#   corresponding character to replace in the main map.
#   The generator will process them first.
#
# ====== <s/?> - Sub Patterns
#   These keys will point to the 'sub-pattern' section and
#   replace them in the main pattern map. During generation
#   of the compass string, the plugin will look for the
#   corresponding character and process them before the
#   post-process comes in.
#
# ====== Post Processing
#   %str% represents the generated string, post process will
#   not affect the direction of the compass at all, rather
#   only add on gimmicks such as brackets or the cursor
#   function, which is exclusive to post processing.
#
#   Separate keys by using ';'.
#
# ===== Static References
#   This is a work in progress. These values are generated
#   dynamically and it is not recomended that you name a
#   key after them. They can be viewd on references.txt
#
# ==========================================================
themes:
  default:
    meta:
      name: "&lMidnight"
      desc: "&7The default theme.%nl%&7The moon fills you with determination."
    data:
      main-pattern-map: "<S>;<s/sep>;<W>;<s/sep>;<N>;<s/sep>;<E>;<s/sep>"
      function:
        cursor: "&f[;%str%;&f]"
        target: "&9\u2588"
      direct:
        <S>: "&f&l&n S "
        <W>: "&f&l&n W "
        <N>: "&f&l&n N "
        <E>: "&f&l&n E "
      sub-pattern:
        <s/sep>:
          pattern-map: "<1>;<2>;<3>;<3>;<4>;<4>;<4>;<4>;<4>;<4>;<3>;<3>;<2>;<1>"
          <1>: "&0\u2588"
          <2>: "&0\u2593"
          <3>: "&0\u2592"
          <4>: "&0\u2591"
    final:
      pattern-map: "<<>;%str%;<>>"
      <<>: "&f&l["
      <>>: "&f&l]"
  midnight-light:
    meta:
      name: "&lMidnight Light"
      desc: "&7Light the night."
    data:
      main-pattern-map: "<S>;<s/sep>;<W>;<s/sep>;<N>;<s/sep>;<E>;<s/sep>"
      function:
        cursor: "&f[;%str%;&f]"
        target: "&9\u2588"
      direct:
        <S>: "&f&l&n S "
        <W>: "&f&l&n W "
        <N>: "&f&l&n N "
        <E>: "&f&l&n E "
      sub-pattern:
        <s/sep>:
          pattern-map: "<1>;<2>;<3>;<3>;<4>;<4>;<4>;<4>;<4>;<4>;<3>;<3>;<2>;<1>"
          <1>: "&8\u2588"
          <2>: "&8\u2593"
          <3>: "&8\u2592"
          <4>: "&8\u2591"
    final:
      pattern-map: "<<>;%str%;<>>"
      <<>: "&f&l["
      <>>: "&f&l]"
  midnight-mini:
    meta:
      name: "&lMidnight Mini"
      desc: "&7Baby moon-moon."
    data:
      main-pattern-map: "<S>;<s/sep>;<W>;<s/sep>;<N>;<s/sep>;<E>;<s/sep>"
      function:
        cursor: "&f[;%str%;&f]"
        target: "&9\u2588"
      direct:
        <S>: "&f&l&n S "
        <W>: "&f&l&n W "
        <N>: "&f&l&n N "
        <E>: "&f&l&n E "
      sub-pattern:
        <s/sep>:
          pattern-map: "<1>;<2>;<3>;<4>;<3>;<2>;<1>"
          <1>: "&0\u2588"
          <2>: "&0\u2593"
          <3>: "&0\u2592"
          <4>: "&0\u2591"
    final:
      pattern-map: "<<>;%str%;<>>"
      <<>: "&f&l["
      <>>: "&f&l]"
  midnight-color:
    meta:
      name: "&lRespendent"
      desc: "&7What does it mean!?"
    data:
      main-pattern-map: "<S>;<s/sep>;<W>;<s/sep>;<N>;<s/sep>;<E>;<s/sep>"
      function:
        cursor: "&f[;%str%;&f]"
        target: "&f&l\u2588"
      direct:
        <S>: "&f&l&n S "
        <W>: "&f&l&n W "
        <N>: "&f&l&n N "
        <E>: "&f&l&n E "
      sub-pattern:
        <s/sep>:
          pattern-map: "<1>;<2>;<3>;<4>;<5>;<6>;<7>;<8>;<9>;<a>;<b>;<c>"
          <1>: "&4\u2588"
          <2>: "&c\u2593"
          <3>: "&e\u2593"
          <4>: "&6\u2592"
          <5>: "&2\u2592"
          <6>: "&a\u2591"
          <7>: "&b\u2591"
          <8>: "&3\u2592"
          <9>: "&9\u2592"
          <a>: "&1\u2593"
          <b>: "&5\u2593"
          <c>: "&d\u2588"
    final:
      pattern-map: "<<>;%str%;<>>"
      <<>: "&f&l["
      <>>: "&f&l]"
  minimal-normal:
    meta:
      name: "&lMinimalistic"
      desc: "&7You keep it simple, I see."
    data:
      main-pattern-map: "<S>;<s/sep>;<W>;<s/sep>;<N>;<s/sep>;<E>;<s/sep>"
      function:
        cursor: "&f[;%str%;&f]"
        target: "&6&l\u272A"
      direct:
        <S>: "&f&lS"
        <W>: "&f&lW"
        <N>: "&f&lN"
        <E>: "&f&lE"
      sub-pattern:
        <s/sep>:
          pattern-map: "<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>"
          <1>: "  "
    final:
      pattern-map: "<<>;%str%;<>>"
      <<>: "&f&l["
      <>>: "&f&l]"
  minimal-staff:
    meta:
      name: "&lMinimalistic Staff"
      desc: "&7All compact and cozy!"
    data:
      main-pattern-map: "<M>;<s/sep>;<M>;<s/sep>;<M>;<s/sep>;<M>;<s/sep>"
      function:
        cursor: "&f[;%str%;&f]"
        target: "&6|"
      direct:
        <M>: "&f|"
      sub-pattern:
        <s/sep>:
          pattern-map: "<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>;<1>"
          <1>: "&8|"
    final:
      pattern-map: "<<>;%str%;<>>"
      <<>: "&f["
      <>>: "&f]"
  locational-red:
    meta:
      name: "&lLocational &c&lRed"
      desc: "&7Location to the nearest volcano!"
    data:
      main-pattern-map: "None"
    final:
      pattern-map: "&4&lYou:&f %player_x% %player_y% %player_z% &c\u27A4&f %compassance_p_target_distance% &c\u27A4 &4&lTarget:&f %compassance_p_target_location%"
  locational-blue:
    meta:
      name: "&lLocational &3&lBlue"
      desc: "&7Directions to the North Pole!"
    data:
      main-pattern-map: "None"
    final:
      pattern-map: "&3&lYou:&f %player_x% %player_y% %player_z% &b\u27A4&f %compassance_p_target_distance% &b\u27A4 &3&lTarget:&f %compassance_p_target_location%"
  time-compass:
    meta:
      name: "&lTime Compass"
      desc: "&7Break me free!"
    data:
      main-pattern-map: "None"
    final:
      pattern-map: "&f%date_MMMM d, yyyy% &8&m-----&f %date_h:mm:ss a z%"
